apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
data:
  rabbitmq.conf: |
    # Default user and password
    default_user = guest
    default_pass = guest

    # Enable management plugin
    management.tcp.port = 15672
    management.tcp.ip   = 0.0.0.0

    # Set memory high watermark
    vm_memory_high_watermark.relative = 0.7

    # Enable metrics
    prometheus.tcp.port = 15692
